spring:
  profiles:
    active: local
    include:
      - const
      - db
      - security
      - jwt
      - ssl

  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 최대 크기
      max-request-size: 10MB # 요청한 파일 전체의 최대 크기

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
